# Generated by Django 3.2.4 on 2021-06-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Age',
            field=models.IntegerField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Email',
            field=models.EmailField(default='', max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Name',
            field=models.CharField(default='', max_length=99, null=True),
        ),
    ]
