# Generated by Django 3.2.4 on 2021-06-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_auto_20210625_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Introduce',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Pub_Date',
        ),
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.IntegerField(default=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='', max_length=253, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='introduce',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='', max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
