# Generated by Django 3.2.3 on 2021-06-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemberApp', '0002_alter_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
